import {ListItemDesc} from "../interfaces/interfaces";

export const CONSTS = {
    NAV_TITLE: "עמוד הבית",
    GENERATE_TEAMS_BTN: "צור קבוצות",
    LIST_EMPTY_TEXT: "התחל להזין שחקנים",
    MODAL_MAIN_TITLE: "?כמה קבוצות",
    MODAL_RANDOM: "מיון אקראי",
    MODAL_RATING_SORT: "מיון לפי דירוג",
    MODAL_CANCEL: "ביטול",
    ACTIVE_PLAYER: "פעיל",
    NOT_ACTIVE_PLAYER: "לא פעיל",
    NOT_POSSIBLE_RESPONSE: "- כמות הקבוצות צריכה להיות קטנה מ",
    TEAMS_RESULTS: "!הקבוצות שלך",
    BACK_HOME_PAGE: "חזור",
    TEAM_NUMBER: "קבוצה מספר ",
    ERROR_MESSAGE: "נא למלא שם שחקן ודירוג(0-10)",
};

export const dummyListItems: ListItemDesc[] = [
    {
        playerName: "אוריאל לוי",
        rating: 8,
        isActive: true,
        isEditMode: false,
        id: "6",
    },
    {
        playerName: "איתי כהן",
        rating: 7,
        isActive: true,
        isEditMode: false,
        id: "4444444",
    },
    {
        playerName: "אור מרכוס",
        rating: 4,
        isActive: true,
        isEditMode: false,
        id: "2",
    },
    {
        playerName: "יוני אברהם",
        rating: 8,
        isActive: true,
        isEditMode: false,
        id: "3",
    },
    {
        playerName: "מתן עין אלי",
        rating: 6,
        isActive: true,
        isEditMode: false,
        id: "4",
    },
    {
        playerName: "גילי גולברי",
        rating: 9,
        isActive: true,
        isEditMode: false,
        id: "5",
    },
    {
        playerName: "תום שחר",
        rating: 9,
        isActive: true,
        isEditMode: false,
        id: "512",
    },
    {
        playerName: "אסי",
        rating: 8,
        isActive: true,
        isEditMode: false,
        id: "101010",
    },
    {
        playerName: "אלעד עזר",
        rating: 5,
        isActive: true,
        isEditMode: false,
        id: "767876",
    },
    {
        playerName: "אור עזרא",
        rating: 7,
        isActive: true,
        isEditMode: false,
        id: "29222192",
    },
    {
        playerName: "ניר כחלון",
        rating: 4,
        isActive: true,
        isEditMode: false,
        id: "295445492",
    },
    {
        playerName: "יקיר סרוסי",
        rating: 3,
        isActive: true,
        isEditMode: false,
        id: "29292",
    },
    {
        playerName: "טולי",
        rating: 7,
        isActive: true,
        isEditMode: false,
        id: "293443392",
    },
    {
        playerName: "עומר גולברי",
        rating: 8,
        isActive: true,
        isEditMode: false,
        id: "296665592",
    },
    {
        playerName: "דניאל רחמים",
        rating: 9,
        isActive: true,
        isEditMode: false,
        id: "2992",
    },
    {
        playerName: "סער שטיגל",
        rating: 4,
        isActive: true,
        isEditMode: false,
        id: "2994542",
    },
    {
        playerName: "רן ואזה",
        rating: 8,
        isActive: true,
        isEditMode: false,
        id: "29967672",
    },
    {
        playerName: "דניאל חריט",
        rating: 8,
        isActive: true,
        isEditMode: false,
        id: "2555992",
    },
    {
        playerName: "אוהד דלהוב",
        rating: 7,
        isActive: true,
        isEditMode: false,
        id: "293434392",
    },
    {
        playerName: "רן אביב",
        rating: 7,
        isActive: true,
        isEditMode: false,
        id: "21212",
    },
];

