export const CONSTS = {
    NAV_TITLE: "עמוד הבית",
    GENERATE_TEAMS_BTN: "צור קבוצות",
    LIST_EMPTY_TEXT: "התחל להזין שחקנים",
    MODAL_MAIN_TITLE: "?כמה קבוצות",
    MODAL_RANDOM: "מיון אקראי",
    MODAL_RATING_SORT: "מיון לפי דירוג",
    MODAL_CANCEL: "חזור",
    ACTIVE_PLAYER: "פעיל",
    NOT_ACTIVE_PLAYER: "לא פעיל",
    NOT_POSSIBLE_RESPONSE: "- כמות הקבוצות צריכה להיות קטנה מ",
    TEAMS_RESULTS: "!הקבוצות שלך",
    BACK_HOME_PAGE: "חזור",
    TABLE_PAGE: "טבלה",
    TEAM_NUMBER: "קבוצה",
    TEAMS: "קבוצות",
    ERROR_MESSAGE: "נא למלא שם שחקן ודירוג תקינים",
    ADD_SECTION_TITLE: ":צור שחקן",
    PLAYER_NAME_PLACEHOLDER: "הזן שם שחקן (עד 15 אותיות)",
    PLAYER_RATE_PLACEHOLDER: "הזן דירוג שחקן (0-10)",
};

export const COLORS = [
    "שחור",
    "לבן",
    "אדום",
    "כתום",
    "ירוק",
    "כחול",
    "צהוב",
    "סגול",
    "תכלת",
    "ורוד",
    "אפור",
    "טורקיז",
]