export const CONSTS = {
    NAV_TITLE: "עמוד הבית",
    GENERATE_TEAMS_BTN: "צור קבוצות",
    LIST_EMPTY_TEXT: "התחל להזין שחקנים",
    MODAL_MAIN_TITLE: "?כמה קבוצות",
    MODAL_RANDOM: "מיון אקראי",
    MODAL_RATING_SORT: "מיון לפי דירוג",
    MODAL_CANCEL: "ביטול",
    ACTIVE_PLAYER: "פעיל",
    NOT_ACTIVE_PLAYER: "לא פעיל",
    NOT_POSSIBLE_RESPONSE: "- כמות הקבוצות צריכה להיות קטנה מ",
    TEAMS_RESULTS: "!הקבוצות שלך",
    BACK_HOME_PAGE: "חזור",
    TEAM_NUMBER: "קבוצה מספר ",
    ERROR_MESSAGE: "נא למלא שם שחקן ודירוג(0-10)",
};